openapi: '3.0.3'
info:
  title: Token Authentication API
  version: '0.0.1'
servers:
  - url: https://api.server.test/v1
tags:
  - name: 'auth'
  - name: 'test'

paths:
  /api/auth/signup:
    post:
      tags:
        - 'auth'
      summary: 'Signup new Account'
      description: 'Check existing and Save User to database'
      operationId: signupUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupForm'
      responses:
        '200':
          description: 'Registered successfully!'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
        '400':
          description: 'Bad Request in form! Could not register new User!'

  /api/auth/signin:
    post:
      tags:
        - 'auth'
      summary: 'Login an Account'
      description: 'Authenticate {username, password} and Create JWT string with a secret'
      operationId: signinUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SigninForm'
      responses:
        '200':
          description: 'Authenticated successfully!'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JWTResponse'
        '401':
          description: 'Unauthorized!'

  /api/test/all:
    get:
      tags:
        - 'test'
      summary: 'Public Content'
      description: 'Access enabled to anyone'
      operationId: allAccess
      responses:
        '200':
          description: 'Authenticated successfully!'
          content:
            application/json:
              schema:
                type: string
  
  /api/test/{role}:
    get:
      tags:
        - 'test'
      security:
        - bearerAuth: []
      summary: 'Restrict Content'
      description: 'Access enabled to specific Role'
      operationId: roleAccess
      parameters:
        - name: role
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/EnumRole'
      responses:
        '200':
          description: 'Authenticated successfully!'
          content:
            application/json:
              schema:
                type: string
        '401':
          description: 'Unauthorized!'

components:
  schemas:
    ApiError:
      type: object
      required:
        - timestamp
        - message
      properties:
        timestamp:
          type: string
          format: date-time
        message:
          type: string
        fieldErrors:
          type: array
          items:
            type: string

    SignupForm:
      type: object
      required:
        - 'username'
        - 'email'
        - 'password'
        - 'roles'
      properties:
        username:
          $ref: '#/components/schemas/Username'
        email:
          $ref: '#/components/schemas/Email'
        password:
          $ref: '#/components/schemas/Password'
        roles:
          type: array
          uniqueItems: true
          items:
            $ref: '#/components/schemas/EnumRole'
    SigninForm:
      type: object
      required:
        - 'username'
        - 'password'
      properties:
        username:
          $ref: '#/components/schemas/Username'
        password:
          $ref: '#/components/schemas/Password'
    Email:
      type: string
      format: email
      description: 'User e-mail for contact and to redefine lost password [UNIQUE]'
      example: 'example@example.com'
    Username:
      type: string
      description: 'Name used to refer User [UNIQUE]'
      example: 'ForrestGump1'
      maxLength: 128
      minLength: 6
    Password:
      type: string
      format: password
      description: 'User password to access account'
      example: '1234567890'
      maxLength: 255
      minLength: 6
    EnumRole:
      type: string
      enum:
        - 'ROLE_ADMIN'
        - 'ROLE_MANAGER'
        - 'ROLE_USER'
      description: 'Client permissions'
    JWTResponse:
      type: object
      required:
        - 'token'
        - 'type'
        - 'username'
        - 'roles'
      properties:
        token:
          type: string
        type:
          $ref: '#/components/schemas/EnumToken'
        username:
          $ref: '#/components/schemas/Username'
        roles:
          type: array
          items:
            $ref: '#/components/schemas/EnumRole'
    EnumToken:
      type: string
      enum:
        - 'Bearer'
    UserId:
      type: integer
      format: int64
    MessageResponse:
      type: string
  
  securitySchemes:
    bearerAuth:
      scheme: bearer
      type: http
      bearerFormat: JWT
