version: '3.9'
name: authentication-dev
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: no
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - 8000:8000
    networks:
      - server
  
  postgres:
    image: postgres:alpine
    restart: no
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - data:/var/lib/postgresql/data
    networks:
      - server
  
  adminer:
    image: adminer:standalone
    restart: no
    depends_on:
      - postgres
    ports:
      - 9000:8080
    networks:
      - server
   
volumes:
  data:
    name: auth-dev
    
networks:
  server:
    driver: bridge