version: '3.9'
name: authentication
services:
  server:
    image: juliocauan/authentication:latest
    depends_on:
      - postgres
    env_file:
      - .env
      - .env.secret
    ports:
      - 8080:8443
    networks:
      - server
  
  postgres:
    image: postgres:alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - server
      - adminer
  
  adminer:
    image: adminer:standalone
    depends_on:
      - postgres
    ports:
      - 8081:8080
    networks:
      - adminer
   
volumes:
  data:
    name: authentication
    
networks:
  server:
    driver: bridge
  adminer:
    driver: bridge