version: '3.9'
name: authentication-back-end-dev
services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=auth-db-dev
    ports:
      - 5432:5432
    volumes:
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-dev:/var/lib/postgresql/data
  
  adminer:
    image: adminer:standalone
    restart: always
    depends_on:
      - postgres
    ports:
      - 9000:8080
   
volumes:
  db-dev:
    name: auth-db-dev
    