version: '3.9'
name: authentication-test
services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=sa
      - POSTGRES_DB=auth-test
    ports:
      - 5434:5432
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
    name: auth-test
