version: '3.9'
name: authentication-dev
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    env_file:
      - .env.dev
    ports:
      - 8080:8080
    networks:
      - server
  
  db:
    image: postgres:alpine
    env_file:
      - .env.dev
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - server
      - adminer
  
  adminer:
    image: adminer:standalone
    depends_on:
      - db
    ports:
      - 8081:8080
    networks:
      - adminer
   
volumes:
  data:
    name: auth-dev
    
networks:
  server:
    driver: bridge
  adminer:
    driver: bridge