version: '3.9'
name: authentication
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 8000:8443
    networks:
      - server
  
  db:
    image: postgres:alpine
    env_file:
      - .env
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - server
      - adminer
  
  adminer:
    image: adminer:standalone
    depends_on:
      - db
    ports:
      - 8001:8080
    networks:
      - adminer
   
volumes:
  data:
    name: authentication
    
networks:
  server:
    driver: bridge
  adminer:
    driver: bridge