version: '3.9'
name: authentication-dev
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - 8000:8000
    networks:
      - server
  
  postgres:
    image: postgres:alpine
    env_file:
      - .env
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - data:/var/lib/postgresql/data
    networks:
      - server
  
  adminer:
    image: adminer:standalone
    depends_on:
      - postgres
    ports:
      - 9000:8080
    networks:
      - server
   
volumes:
  data:
    name: auth-dev
    
networks:
  server:
    driver: bridge