version: '3.9'
name: authentication-test
services:
  postgres:
    image: postgres:alpine
    restart: no
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=sa
      - POSTGRES_DB=auth-test
    ports:
      - 5434:5432
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - data:/var/lib/postgresql/data

volumes:
  data:
    name: auth-test
