spring:
    profiles:
        active: dev
    datasource:
        driver-class-name: org.postgresql.Driver
    mustache:  
        check-template-location: false
    jpa:
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        open-in-view: false
        show-sql: false
        defer-datasource-initialization: false
    sql:
        init:
            mode: never
    mail:
        host: smtp.gmail.com
        port: 587
        username: jcam.test01@gmail.com
        password: qsdbnzwwmoznzcee
        properties:
            mail:
                smtp:
                    useSSL: true
                    auth: true
                    starttls:
                        enable: true
    