server:
    port: 8443

spring:
    mail:
        host: smtp.gmail.com
        port: 587
        username: ${APP_EMAIL_USERNAME}
        password: ${APP_EMAIL_PASSWORD}

REGISTER_ADMIN_PASSWORD: ${REGISTER_ADMIN_PASSWORD:"@Admin1234"}