server:
    port: 8000
    
spring:
    datasource:
        url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=true
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
    mustache:  
        check-template-location: false
    jpa:
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        open-in-view: false
        show-sql: false
        defer-datasource-initialization: false
    sql:
        init:
            mode: never
    mail:
        host: smtp.gmail.com
        port: 587
        username: ${SENDER_USERNAME}
        password: ${SENDER_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
    config:
        location: file:.env 