spring:
    profiles:
        active: prod
    datasource:
        url: jdbc:postgresql://postgres:5432/${DB}?useSSL=true
        username: ${USER}
        password: ${PASSWORD}
    jpa:
        open-in-view: false
        defer-datasource-initialization: true
    sql:
        init:
            mode: always
