server:
    port: ${APP_PORT}

spring:
    datasource:
        url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=true
        username: ${DB_USER}
        password: ${DB_PASSWORD}
    mail:
        username: ${APP_EMAIL_USERNAME}
        password: ${APP_EMAIL_PASSWORD}

domain: http://localhost:4200