spring:
    profiles:
        active: prod
    datasource:
        url: jdbc:postgresql://postgres:5432/${POSTGRES_DB}?useSSL=true
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
    jpa:
        open-in-view: false
        defer-datasource-initialization: true
    sql:
        init:
            mode: always
    mail:
        protocol: smtp
        properties:
            mail:
                smtp:
                    useSSL: true
                    auth: true
                    starttls:
                        enable: true
