server:
    port: ${PORT}
    
spring:
    datasource:
        url: ${DB_URL}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
    mustache:  
        check-template-location: false
    jpa:
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        open-in-view: false
        show-sql: false
        defer-datasource-initialization: false
    sql:
        init:
            mode: never
