server:
    port: ${APP_PORT}

spring:
    datasource:
        url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=true
        username: ${DB_USER}
        password: ${DB_PASSWORD}
    mail:
        username: jcam.test01@gmail.com
        password: qsdbnzwwmoznzcee
    