spring:
    datasource:
        url: jdbc:postgresql://postgres:${DB_PORT_DEV}/${DB_NAME_DEV}?useSSL=true
        username: ${DB_USER_DEV}
        password: ${DB_PASSWORD_DEV}
    mail:
        username: ${APP_EMAIL_USERNAME_DEV}
        password: ${APP_EMAIL_PASSWORD_DEV}
        
domain: ${APP_DOMAIN_DEV}