spring:
    profiles:
        active: prod
    datasource:
        url: jdbc:${DB}://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=true
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    jpa:
        open-in-view: false
        defer-datasource-initialization: true
    sql:
        init:
            mode: always
