version: '3.9'

services:

  postgres:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=dev-auth-db
      - POSTGRES_USER=root
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/postgresql/data

volumes:
  db:
    