name: Docker Deploy

on:
  workflow_call:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Docker Build
      uses: docker/setup-buildx-action@v2.4.0
      
    - name: Restore build cache
      uses: actions/cache/restore@v3
      with:
        path: |
          ./target/authentication-*.jar
          ./Dockerfile
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v4.0.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/authentication:${{github.ref_name}}
    