name: Docker

on:
  workflow_call:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: setup Docker Build
      uses: docker/setup-buildx-action@v2.4.0
      
    - name: Download Authentication Artifact
      uses: actions/download-artifact@v3.0.2
      with:
        name: authentication
      
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: juliocauan
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v4.0.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: juliocauan/authentication:${{github.ref_name}}
    