name: Docker Application Deployment

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Docker Build
      uses: docker/setup-buildx-action@v3
    
    - name: Restore Cache .JAR
      uses: actions/cache/restore@v3
      with:
        path: './target/authentication-*.jar'
        key: ${{ runner.os }}-jar-${{ hashFiles('**/authentication-*.jar') }}

    - name: Restore Cache Dockerfile
      uses: actions/cache/restore@v3
      with:
        path: './Dockerfile'
        key: ${{ runner.os }}-dockerfile-${{ hashFiles('./Dockerfile') }}

    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/authentication:${{github.ref_name}}
    