name: Java CI with Maven

on:
  push:
    branches: [ 'main', 'develop']
  pull_request:
    branches: [ 'main', 'develop' ]

jobs:
  clean_artifacts:
    runs-on: ubuntu-latest
    steps:
    - name: Delete old Artifacts
      uses: actions/github-script@v6
      id: artifact
      with:
        script: |
          const res = await github.rest.actions.listArtifactsForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
          })
          res.data.artifacts
            .filter(({ name }) => name === 'package')
            .forEach(({ id }) => {
              github.rest.actions.deleteArtifact({
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: id,
              })
            })

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
        submodules: recursive
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
        cache: maven

    - name: Build Database
      run: docker compose -f "docker-compose-test.yml" up -d --build
    
    - name: Test and Package with Maven
      run: mvn -B package --file pom.xml
    
    - name: Cache .JAR
      uses: actions/cache/save@v3
      with:
        path: './target/authentication-*.jar'
        key: ${{ runner.os }}-jar-${{ hashFiles('**/authentication-*.jar') }}

    - name: Cache Dockerfile
      uses: actions/cache/save@v3
      with:
        path: './Dockerfile'
        key: ${{ runner.os }}-dockerfile-${{ hashFiles('./Dockerfile') }}
  
  analytics:
    needs: clean_artifacts
    uses: ./.github/workflows/analytics.yml
    secrets: inherit

  docker:
    needs: ["build", "analytics"]
    uses: ./.github/workflows/docker.yml
    secrets: inherit
