name: Java CI with Maven

on:
  push:
    branches: [ 'master', 'develop' ]
  pull_request:
    branches: [ 'master', 'develop' ]

jobs:

  test_and_build:
    runs-on: ubuntu-latest
    env:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: test-auth-db
      DB_USER: root
      DB_PASSWORD: secret
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: webfactory/ssh-agent
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Update submodules
      run: |
        git submodule sync --recursive
        git submodule update --init --recursive

    - name: Build and Create Database
      run: docker compose -f "docker-compose.yml" up -d --build
    
    - name: Test and Package with Maven
      run: mvn -B package --file pom.xml

    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@v2.0.1
      
    - name: Delete Old Artifacts
      uses: actions/github-script@v6
      id: artifact
      with:
        script: |
          const res = await github.rest.actions.listArtifactsForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
          })

          res.data.artifacts
            .forEach(({ id }) => {
              github.rest.actions.deleteArtifact({
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: id,
              })
            })

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: authentication
        path: target/*.jar

  upload_project_image:
    needs: test_and_build
    uses: ./.github/workflows/docker.yml
    secrets: inherit
