name: Java CI with Maven

on:
  push:
    branches: [ 'main', 'develop']
  pull_request:
    branches: [ 'main', 'develop' ]

jobs:
  test_and_package:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
        cache: maven

    - name: Set up SSH Agent
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Update Git Submodules
      run: git submodule update --init --recursive

    - name: Build Database
      run: docker compose -f "docker-compose-test.yml" up -d --build
    
    - name: Test and Package with Maven
      run: mvn -B package --file pom.xml

        
    - name: Upload Workplace Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: workplace
        path: .

    - name: Upload Authentication Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: authentication
        path: target/*.jar

  upload_image:
    needs: test_and_package
    uses: ./.github/workflows/docker.yml
    secrets: inherit

  dependency_graph:
    runs-on: ubuntu-latest
    needs: test_and_package
    steps:
    - name: Download Workplace Artifact
      uses: actions/download-artifact@v3.0.2
      with:
        name: workplace
    
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@v2.0.1

  delete_artifacts:
    runs-on: ubuntu-latest
    needs: 
      - upload_image
      - dependency_graph
    steps:
    - name: Delete Artifacts
      uses: actions/github-script@v6
      id: artifact
      with:
        script: |
          const res = await github.rest.actions.listArtifactsForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
          })

          res.data.artifacts
            .filter(({ name }) => name === 'package')
            .forEach(({ id }) => {
              github.rest.actions.deleteArtifact({
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: id,
              })
            })