name: Check Application Vulnerabilities

on:
  workflow_call:
  
jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Submit Dependency Snapshot
      uses: advanced-security/maven-dependency-submission-action@v3
      
    - name: Dependency Review
      uses: actions/dependency-review-action@v3
      with:
        fail-on-severity: low
        vulnerability-check: true
        base-ref: main
        head-ref: ${{ github.event.before }}
        
  security:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/maven-3-jdk-17@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=high