name: Check Application Vulnerabilities

on:
  workflow_call:
  
jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
        submodules: recursive
    
    - name: Submit Dependency Snapshot
      uses: advanced-security/maven-dependency-submission-action@v3
      
    - name: Dependency Review
      uses: actions/dependency-review-action@v3
      with:
        fail-on-severity: low
        vulnerability-check: true
        base-ref: main
        head-ref: ${{ github.event.before }}
        
  security:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
        submodules: recursive
    
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/maven-3-jdk-17@master
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=low --sarif --sarif-file-output=snyk.sarif --all-projects
    
    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: snyk.sarif